-- SUB QUERY

SELECT [Order ID]
FROM SalesOrder
GROUP BY [Order ID]
HAVING SUM(SALES)>
(
SELECT AVG(ORDER_SALES )
FROM 
(SELECT [Order ID],SUM(SALES) AS ORDER_SALES 
FROM SalesOrder
GROUP BY [Order ID]) ORDER_AGG)

SELECT * FROM SalesOrder WHERE [Order ID]='CA-2014-100090'

SELECT * FROM DEPT;
SELECT * FROM EMP;

SELECT *
FROM EMP 
WHERE dept_id NOT IN (SELECT DEP_ID FROM DEPT)

SELECT DEP_ID FROM DEPT;

select 
* from emp 
e left join dept d 
on e.dept_id =d.dep_id
WHERE D.DEP_ID IS NULL;


SELECT A.*,B.*
FROM
(SELECT [Order ID],SUM(SALES) AS ORDER_SALES
FROM SalesOrder
GROUP BY [Order ID]) A
INNER JOIN
(SELECT AVG(ORDER_SALES ) AS AVG_ORDER_VALUE
FROM 
(SELECT [Order ID],SUM(SALES) AS ORDER_SALES 
FROM SalesOrder
GROUP BY [Order ID]) ORDER_AGG)B
ON 1=1
WHERE ORDER_SALES>AVG_ORDER_VALUE;
-------
SELECT [Order ID]
FROM SalesOrder
GROUP BY [Order ID]
HAVING SUM(SALES)>
(
SELECT AVG(ORDER_SALES )
FROM 
(SELECT [Order ID],SUM(SALES) AS ORDER_SALES 
FROM SalesOrder
GROUP BY [Order ID]) ORDER_AGG)







